version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - web-db 
      - cache 
      

  web-db:
    image: postgres:14-alpine
    volumes:
      - e-learning:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=course
      - POSTGRES_DB=course_dev
  
  cache:
    image: memcached
    ports:
      - "11211:11211"
    entrypoint: 
      - memcached 
      - -m 64
      
    


volumes:
  e-learning:
    external: true