# Generated by Django 3.0.14 on 2022-02-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='fiel',
            new_name='file',
        ),
    ]
